//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResources.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalEntry
    {
        public int EntryNumber { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNo { get; set; }
        public string SenderId { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string ApproverId { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public string Status { get; set; }
    }
}
