//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResources.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeeLedgerEntries = new HashSet<EmployeeLedgerEntry>();
            this.Leaves = new HashSet<Leaf>();
            this.Users = new HashSet<User>();
        }
    
        public string EmployeeNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Initials { get; set; }
        public string FullName { get; set; }
        public string IDNumber { get; set; }
        public string PassportNumber { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PINNo { get; set; }
        public string NSSFNo { get; set; }
        public string NHIFNo { get; set; }
        public string HELBNo { get; set; }
        public string Religion { get; set; }
        public string Citizenship { get; set; }
        public byte[] Picture { get; set; }
        public string PostalAddress { get; set; }
        public string ResidentialAddress { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public string HomePhoneNumber { get; set; }
        public string CellularPhoneNumber { get; set; }
        public string WorkPhoneNumber { get; set; }
        public string EMail { get; set; }
        public string CompanyEMail { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Disabled { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public Nullable<System.DateTime> SuspensionDate { get; set; }
        public Nullable<System.DateTime> DemisedDate { get; set; }
        public Nullable<System.DateTime> Retirementdate { get; set; }
        public Nullable<System.DateTime> RetrenchmentDate { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public Nullable<System.DateTime> EndOfContractDate { get; set; }
        public System.DateTime Date_Of_Joining_the_Company { get; set; }
        public Nullable<System.DateTime> Date_Of_Leaving_the_Company { get; set; }
        public Nullable<int> Termination_Grounds { get; set; }
        public string Bank { get; set; }
        public string BankBranch { get; set; }
        public string BankAccountNumber { get; set; }
        public string Department_Name { get; set; }
        public decimal AnnualLeaveDaysEntitled { get; set; }
        public string HROrgUnit { get; set; }
        public string HRPosition { get; set; }
        public int CurrentYear { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLedgerEntry> EmployeeLedgerEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leaf> Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
