//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResources.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leaf()
        {
            this.Attachments = new HashSet<Attachment>();
            this.LeaveRecalls = new HashSet<LeaveRecall>();
        }
    
        public string DocumentNo { get; set; }
        public string LeaveType { get; set; }
        public string SelectionType { get; set; }
        public string StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string LeaveDates { get; set; }
        public int LeaveDaysApplied { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string EmployeeNo { get; set; }
        public string ApprovalStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRecall> LeaveRecalls { get; set; }
    }
}
