//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResources.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberSery
    {
        public string Code { get; set; }
        public string Description { get; set; }
        public string StartingNumber { get; set; }
        public string EndingNumber { get; set; }
        public string LastUsedNumber { get; set; }
    }
}
